# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe10fd635b877a95d2174cb1da4c6bd5efdf89fa856f2e65bb8208f7c6db339f0302b46fbc1bf20c674b4f4d48c6507b331dee5b1b3b61e04278451654f99514

test:
  secret_key_base: fed739b58c027546a5eab58e2abb387a5d5c5804e2baa3b67606f56e4437914538dc22f953a5d76de53ceb0d695c087b61b5ff7237d05048f439769ace734728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  hoge_key: <%= ENV['HOGE_KEY'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
